### ISSUE TITLE
Allow Setting ProtonVPN Tier (Free, Basic, Plus, Visionary) through environment Variables

### ISSUE THREAD

**Issue by CC3301** [HaruVON/qbit-vpn#2]
It would be great to be able to tell the protonvpn-cli Client which Tier to use.

It should be rather simple to implement:
https://github.com/HaruVON/qbit-vpn/blob/8a0b2b793f214b7982b9f1df1a471a59efbd18b7/scripts/default-script.exp#L65

Really only this line and the one below would need to be changed. I think this is very similar to the way the username and password are handled.

Would be nice of you to implement this. I can provide you with a diff, if that makes it easier/faster.

**Comment by HaruVON** [comment]
Yeah, I can add this
